logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password: dbadmin
    username: dbadmin
  jpa:
    defer-datasource-initialization: true
  mustache:
    check-template-location: false
  sql:
    init:
      mode: always
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,pl.base
